CREATE TABLE `quotes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`customerName` varchar(255) NOT NULL,
	`customerEmail` varchar(320) NOT NULL,
	`customerPhone` varchar(50) NOT NULL,
	`boatLength` int NOT NULL,
	`boatType` varchar(100) NOT NULL,
	`serviceLocation` varchar(255) NOT NULL,
	`estimatedTotal` int NOT NULL,
	`depositAmount` int NOT NULL DEFAULT 25000,
	`paymentStatus` enum('pending','paid','refunded') NOT NULL DEFAULT 'pending',
	`stripePaymentIntentId` varchar(255),
	`paidAt` timestamp,
	`requiresManualReview` int NOT NULL DEFAULT 0,
	`reviewReasons` text,
	`reviewedAt` timestamp,
	`servicesConfig` text NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `quotes_id` PRIMARY KEY(`id`)
);
